# +-------------------------------------------------------+
# | Configuración de UserLogin.                           |
# | Para preguntas o reportar bugs, unirte a mi           |
# | servidor de Discord aquí: https://discord.gg/HdnP32P  |
# +-------------------------------------------------------+

# Revisar por nuevas versions
checkUpdates: true

# Archivo de lenguaje a usar
lang: 'en_US'

# Intervalo en segundos para repetir el mensaje de bienvenida (-1 para desactivar)
repeatingWelcomeMsg: -1

# Opciones de kickeo automático
timeout:

  # Activar/desactivar el kickeo automático
  enabled: true

  # Tiempo de espera para el kickeo
  time: 60


# Opciones para las contraseñas
password:

  # Encriptar contraseñas al almacenarlas en playerData.yml/base de datos MySQL
  encrypt: false

  # Caracteres mínimos que debe tener una contraseña
  minCharacters: 4


# Habilitar/desabilitar restricciones para jugadores no-logeados
restrictions:

  # Mensajes de chat
  chat: false

  # Uso de comandos (Aparte de /login y /register)
  commands: false

  # Movimiento del jugador
  movement: false
  # Frecuencia para avisar al jugador de la restricción (-1 para desactivar)
  move-warn-frequency: 20

  # Romper bloques
  blockBreak: false

  # Soltar items
  itemDrop: false

  # Recoger items
  itemPickup: false


# Habilitar/deshabilitar ciertos teletransportes
teleports:

  # Guardar las posiciones de los jugadores al desconectarse
  savePosition: false
  # El modo savePosition teletransporta al jugador
  # a su última posición antes de haberse desconectado

  # Teletransportar jugadores al punto de login al conectarse
  toLogin: true

  # Teletransportar al jugador al punto de spawn cuando se logee (Modo normal, sin BungeeCord)
  toSpawn: true


# Opciones de recuerdo de IP de jugadores (Sólo en modo no-BungeeCord)
ipRecords:

  # Permitir que los jugadores se logeen automáticamente
  # si entran con la misma dirección IP consecutivamente
  enabled: false

  # Tiempo (segundos) en el que se recordará
  # la dirección IP de los jugadores
  delay: 30


# Alias para comandos (Formato: [ alias1, alias2, alias3... ])
commandAliases:
  login: [ ]
  register: [ ]
  userlogin: [ ul ]


# Opciones de BungeeCord
bungeeCord:

  # Activar/desactivar BungeeCord
  enabled: false

  # Servidor al cual enviar al jugador cuando se logee
  spawnServer: 'LOBBY'


# Opciones de título de bienvenida
joinTitle:

  # Activar/desactivar
  enabled: false

  # Duración del título (ticks)
  fadeIn: 10
  duration: 70
  fadeOut: 20


# Opciones de MySQL
mysql:

  # Usar una base de datos MySQL para guardar los datos en lugar de archivos YAML
  enabled: false

  # Intervalo (en segundos) entre el cual los datos serán enviados a la base de datos MySQL
  saveInterval: 300

  # Usar SSL para la conexión
  useSSL: false

  # Base de datos y tabla para almacenar los datos
  database: 'userlogin_data'
  table: 'player_data'

  # Credenciales para acceder a la base de datos MySQL
  host: 'localhost'
  username: 'root'
  password: 'password'
  port: 3306
