# ----------------------------------------------------
# | Configuration file for UserLogin.                 |
# | For any doubts, you can join my Discord server   |
# | with this link: https://discord.gg/HdnP32P       |
# ----------------------------------------------------

# Enable update checking
checkUpdates: true

# Language file to load
lang: 'en_US'

# Timeout-kicking settings
timeout:

  # Enable/disable timeout kicking
  enabled: true

  # Timeout delay in seconds
  time: 60


# Password options
password:

  # Encrypt passwords when saving them to playerData.yml/MySQL database
  encrypt: false

  # Minimum characters that a password must have
  minCharacters: 4


# Enable/disable restrictions for non-logged in players
restrictions:

  # Chat messages
  chat: false

  # Command execution
  commands: false

  # Player movement
  movement: false

  # Block breaking
  blockBreak: false

  # Drop items
  itemDrop: false

  # Pick up items
  itemPickup: false


# Enable/disable certain teleports
teleports:

  # Save players' position on logout
  save-position: false
  # The save-position mode teleports the player
  # to their last position when they log in.

  # Teleport players to login location on join
  toLogin: true

  # Teleport players to spawn when logged in (Normal mode, non-BungeeCord only)
  toSpawn: true


# Player IP record options
ipRecords:

  # Allow players to bypass login if they enter with the
  # same IP address consecutively
  enabled: false

  # Time (seconds) in which the player's IP
  # will be remembered
  delay: 30


# BungeeCord options
bungeeCord:

  # Enable BungeeCord functionalities
  enabled: false

  # Server to send the player when logged in
  spawnServer: 'LOBBY'

# Join title settings
joinTitle:

  # Send players a title message on join
  enabled: false

  # Fade duration (ticks)
  fadeIn: 10
  duration: 70
  fadeOut: 20


# MySQL options
mysql:

  # Replace YAML storage with MySQL storage
  enabled: false

  # Interval (in seconds) between which local data will be saved to the database
  saveInterval: 300

  # Use SSL for database connection
  useSSL: false

  # Database and table to store the data in
  database: 'userlogin_data'
  table: 'player_data'

  # Connection credentials and information
  host: 'localhost'
  username: 'root'
  password: 'password'
  port: 3306
