name: UserLogin
version: ${project.version}
main: com.elchologamer.userlogin.UserLogin
authors: [ElCholoGamer]
description: A login security system for you server
website: www.spigotmc.org
commands:
  userlogin:
    description: The main command for UserLogin
    usage: '§cCorrect usage: /<command> <sub> (Use /ul help for more)'
    aliases: [ul]
    permission: ul.userlogin
  register:
    description: Registers your user with the given password
    usage: '§cCorrect usage: /<command> <password> <password>'
    aliases: [reg]
  login:
    description: Logs in your user with the given password
    usage: '§cCorrect usage: /<command> <password>'
    aliases: [log]