name: UserLogin
version: ${project.version}
main: me.elcholostudios.userlogin.UserLogin
api-version: 1.16
authors: [ElCholoGamer]
description: A simple to use login system for your server!
website: www.spigotmc.org
commands:
  setlogin:
    description: Set the login spawn
    usage: /setlogin
  setlobby:
    description: Set destination lobby after login
    uasge: /setlobby
  register:
    description: Register your account on the server
    usage: /register <password> <password>
  login:
    description: Log in to the server with your password
    usage: /command <password>
  reloadlogin:
    description: Reload configuration files for UserLogin plugin
    usage: /command