name: 'UserLogin'
version: '${project.version}'
main: 'com.elchologamer.userlogin.UserLogin'
author: 'ElCholoGamer'
description: 'A simple-to-use authentication system.'
website: 'https://www.spigotmc.org/resources/userlogin.80669/'
softdepend: ['FastLogin']

permissions:
  ul.*:
    description: 'Permission to use all UserLogin commands'
    default: 'op'
    children:
      ul.userlogin:
        description: 'Permission to use the main UserLogin command'
        default: 'op'
        children:
          ul.help:
            description: 'Permission to use the help command'
          ul.reload:
            description: 'Permission to use the reload command'
          ul.set:
            description: 'Permission to use the set command'
          ul.unregister:
            description: 'Permission to use the unregister command'
      ul.login:
        description: 'Permission to use the login command'
        default: true
      ul.register:
        description: 'Permission to use the register command'
        default: true

commands:
  userlogin:
    description: 'The main command for UserLogin'
    permission: 'ul.userlogin'
  login:
    description: 'Logs in your user with the given password'
    permission: 'ul.login'
  register:
    description: 'Registers your user with the given password'
    permission: 'ul.register'
