name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install FastLogin.jar
        run: mvn install:install-file \
          -Dfile=lib/FastLogin.jar \
          -DgroupId=com.github.games647 \
          -Dversion=1.10 \
          -Dpackaging=jar \
          -DgeneratePom=true
      - name: Build with Maven
        run: mvn -B --no-transfer-progress package
